### PR TITLE
Bug fix for dashboard redirect issue on app reload

### LINKED ISSUE #16: Fix isse with redirect to Dashboard on page reload
Currently the App on reloads redirects to the Dashboard, as it quickly is in a "non-auth" state and the redirect condition in Private App kicks in. Have to reorder some of the mounting logic

### PR DESCRIPTION
**Pull request by dafrie**
This fixes #16. Now the main app component has a `initialized` state. So on app mount (after a reload), the component will first renew the session. Only after this method returned the parsed token, it will continue rendering the component tree, e.g. routes...

### CODE REVIEW

File: src/auth/Auth.ts [hunk 1]
```diff
@@ -84,18 +87,25 @@ class Auth {
...
+   */
+  public renewSession = async (): Promise<void> => {
+    return new Promise((resolve, reject) =>
+      this.auth0.checkSession({}, (err, authResult) => {
+        if (authResult && authResult.accessToken && authResult.idToken) {
+          this.setSession(authResult);
+          resolve();
+        } else if (err) {
+          this.logout();
+          console.log(err);
```
Comment (YanickSchraner) [inline src/auth/Auth.ts]: Is it safe to log those errors?

File: src/auth/Auth.ts [hunk 2]
```diff
@@ -84,18 +87,25 @@ class Auth {
...
+          alert(
+            `Could not get a new token (${err.error}: ${err.errorDescription}).`
```
Comment (YanickSchraner) [inline src/auth/Auth.ts]: Is it safe to print those errors? Or could that get a security issue because we give out unnecessary information?

File: src/auth/Auth.ts (hunk 1 above)
Comment (dafrie) [reply src/auth/Auth.ts]: Hm good point. Since this is the error object received from the callback when renewing a token, this should be safe (I assume auth0 is not sending back any sensitive material). But honestly speaking, the current state there is not very end-user friendly, rather for "debugging"... What do you think? Just ignore the errors? Or should we add something like sentry for monitoring?

Comment (YanickSchraner) [reply src/auth/Auth.ts]: Yes, sentry looks nice. I think the free developer tier should be enough for us? Otherwise, it will be quite expensive. But such a monitoring tool is a must-have in my opinion. Then we could just add a generic error message for the user like "Authentication failed, try again or contact the administrator". And send the full error to our monitoring system.

If ok for you we will delete the console log and replace the alert message for the user with a generic one. Then merge this and create a new issue to add sentry. We can also use sentry for our backend, right?

Comment (dafrie) [reply src/auth/Auth.ts]: yes - I agree. I have removed the console.log's, merge this and create new issues
